.PHONY: all

all: main2_1 main2_2 main2_3 main2_4

main2_1: main2_1.c
	gcc main2_1.c -o main2_1

main2_2: main2_2.c
	gcc main2_2.c -o main2_2

main2_3: main2_3.c
	gcc main2_3.c -o main2_3

main2_4: main2_4.c
	gcc main2_4.c -o main2_4

clean:
	rm -f main2_1 main2_2 main2_3 main2_4 *.o
